# This is a basic workflow to help you get started with Actions

name: Daily sync

on:
  push:
    branches: [ "main" ]
  schedule:
  - cron: "0 18 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: PrepareEnv
        run: |
          sudo apt-get install -y python3 python3-pip wget curl
          pip3 install lastversion

      - name: Version at cache
        uses: actions/cache@v4
        with:
          path: .version
          key: dot-version

      - name: Run a multi-line script
        env: 
          GITEA_HOST:  ${{ secrets.GITEA_HOST }}
          GITEA_USER:  ${{ secrets.GITEA_USER }}
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
        run: |
          ./sync.sh clash-verge-rev/clash-verge-rev "x86_64.rpm$"

      
